task:
  name: Build
  container:
    image: debian:stable
    cpu: 8
    memory: 8G
  build_script:
    - apt update && apt install -y cmake python3 python3-distutils clang lld libxml2-dev libedit-dev liblzma-dev swig3.0 libpython3-dev
    - ln -sf /usr/bin/clang /etc/alternatives/c89
    - ln -sf /usr/bin/clang /etc/alternatives/c99
    - ln -sf /usr/bin/clang /etc/alternatives/cc
    - ln -sf /usr/bin/ld.lld /usr/bin/ld
    - cmake -S llvm -B build -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS="clang;compiler-rt;libcxx;libcxxabi;lldb;lld" -DLLVM_TARGETS_TO_BUILD=X86
    - cmake --build build -j 8
    - mkdir $CIRRUS_WORKING_DIR/root
    - make -C build DESTDIR=$CIRRUS_WORKING_DIR/root install
    - tar czpf $CIRRUS_WORKING_DIR/llvm.tgz -C $CIRRUS_WORKING_DIR/root .
  artifacts:
    path: "llvm.tgz"
